import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";
import { Toaster } from "react-hot-toast";
import VibeRefreshReminder from "./components/VibeRefreshReminder";
import AppLayout from "./components/AppLayout";
import GlobalNotificationManager from "@/src/components/GlobalNotificationManager";

const poppins = Poppins({
  subsets: ["latin"],
  weight: [
    "100",
    "200",
    "300",
    "400",
    "500",
    "600",
    "700",
    "800",
    "900",
  ],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AppLayout>{children}</AppLayout>
        <Toaster/>
        <VibeRefreshReminder />
        <GlobalNotificationManager />
      </body>
    </html>
  );
}
